instance_name: demo017
username: admin
password: admin
assign_group_id: d625dccec0a8016700a222a0f7900d06
assign_group_name: Software

#Notification configuration
#Please set the values for the notification functionality
smtpserver: smtp.yourdomain.com #this is an smtp server in your enviroment where emails can be sent
recipients: recipients@yourdomain.com  #the indended recipients seperated by a comma
fromaddress: sender@yourdomain.com #This is the from address you would like your message to come from

